name: CI
on: [push, pull_request]

jobs:
  build-ghc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5' # Exact version of ghc to use
        cabal-version: '3.0'
    - run: wget https://github.com/ndmitchell/hlint/releases/download/v2.2.4/hlint-2.2.4-x86_64-linux.tar.gz
    - run: tar fvx hlint-2.2.4-x86_64-linux.tar.gz
    - run: runghc Main.hs
    - run: ./hlint-2.2.4/hlint .
